// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Usage struct {
	Hardwareaddr int32
	Starttime    pgtype.Timestamp
	Stoptime     pgtype.Timestamp
	Egress       int32
	Ingress      int32
}
